# Generated by Django 4.2.13 on 2026-04-29 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Score between 1 and 3')),
                ('category', models.CharField(choices=[('Strong', 'Strong'), ('Moderate', 'Moderate'), ('Weak', 'Weak')], max_length=10)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prediction_results',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='questionnaire.predictionresult')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_age', models.PositiveSmallIntegerField(help_text="Parent's age")),
                ('child_age', models.PositiveSmallIntegerField(help_text="Child's age")),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Single-Parent', 'Single-Parent'), ('Extended', 'Extended'), ('Nuclear', 'Nuclear')], help_text='Type of family', max_length=20)),
                ('pq1', models.PositiveSmallIntegerField(help_text="Understand child's point of view")),
                ('pq2', models.PositiveSmallIntegerField(help_text='Pay full attention when child shares problems')),
                ('pq3', models.PositiveSmallIntegerField(help_text='Express emotions clearly and respectfully')),
                ('pq4', models.PositiveSmallIntegerField(help_text='Control anger/frustration during conversations')),
                ('pq5', models.PositiveSmallIntegerField(help_text='Spend quality time talking daily')),
                ('pq6', models.PositiveSmallIntegerField(help_text="Praise or encourage child's efforts")),
                ('pq7', models.PositiveSmallIntegerField(help_text='Listen without interrupting')),
                ('pq8', models.PositiveSmallIntegerField(help_text='Discuss daily activities or school events')),
                ('pq9', models.PositiveSmallIntegerField(help_text='Set clear, consistent boundaries respectfully')),
                ('pq10', models.PositiveSmallIntegerField(help_text='Apologize when wrong')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questionnaire_responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='response',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='questionnaire.questionnaireresponse'),
        ),
    ]
