# Generated by Django 4.2.13 on 2026-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq1',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Understand parent's point of view", null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq10',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Apologize when wrong', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pay full attention when parent shares problems', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq3',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Express emotions clearly and respectfully', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq4',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Control anger/frustration during conversations', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq5',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Spend quality time talking daily', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq6',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Praise or encourage parent's efforts", null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq7',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Listen without interrupting', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq8',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Discuss daily activities or school/office events', null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='cq9',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Follow parent's rules and expectations", null=True),
        ),
    ]
